/**
 * Dados Oficiais e Operacionais do Condomínio Residencial Parque Firenze
 * Cooperativa Habitacional Vida Nova (CHVN) - Embu das Artes / SP
 * Digital Twin Core Database (Georreferenciamento, Hierarquia, Obra, FVS e Ocorrências)
 */

const PARQUE_FIRENZE_DATA = {
    nome: "Condomínio Residencial Parque Firenze",
    realizacao: "Cooperativa Habitacional Vida Nova (CHVN)",
    geo: {
        latitude: -23.6350634,
        longitude: -46.8178467,
        datum: "WGS84 / EPSG:4326",
        altitudeBaseMeters: 805.0,
        municipio: "Embu das Artes - SP",
        cep: "06817-000",
        enderecos: {
            impares: "Av. João Paulo I, 1973 - Jardim dos Oliveiras",
            pares: "Estrada São Judas, 190 - Parque Esplanada"
        }
    },
    totais: {
        torres: 49,
        apartamentos: 9296,
        subcondominios: 7,
        populacaoEstimada: "~28.000 moradores",
        areaTerreno: "> 250.000 m²",
        areaConstruida: "> 1.350.000 m²",
        pistaCooperCiclovia: "2,0 km de extensão"
    },
    grupos: {
        12: {
            id: 12,
            nome: "Grupo 12",
            endereco: "Estrada São Judas, nº 190",
            tipologia: "2 Dormitórios",
            paridade: "par",
            glbSource: "Firenze_Pares.glb",
            torresQtd: 7,
            blocos: ["A", "B", "C", "D", "E", "F", "G"],
            andaresPorTorre: 28,
            aptosPorAndar: 8,
            aptosPorTorre: 224,
            totalApartamentos: 1568,
            subsolos: "2 a 4 pavimentos",
            areaTerreno: "36.174,02 m²",
            areaConstruida: "185.368,30 m²",
            metragemTipo: "79,84 m² (Tipo 2A) a 82,00 m² (Tipo 2B/2C)",
            coberturas: "184,24 m² a 203,79 m² Duplex",
            descricao: "7 torres de 28 andares com subsolos e área de lazer exclusiva.",
            corDestaque: "#3b82f6",
            statusObra: { progressoGeral: 100, fase: "Entregue / Habitado", status: "concluido" },
            posicaoCentro: { x: -160, z: -100 }
        },
        13: {
            id: 13,
            nome: "Grupo 13",
            endereco: "Av. João Paulo I, nº 1973",
            tipologia: "3 Dormitórios",
            paridade: "impar",
            glbSource: "Firenze_Impares.glb",
            torresQtd: 7,
            blocos: ["A", "B", "C", "D", "E", "F", "G"],
            andaresPorTorre: 36,
            aptosPorAndar: 4,
            aptosPorTorre: 144,
            totalApartamentos: 1008,
            subsolos: "3 pavimentos",
            areaTerreno: "29.904,54 m²",
            areaConstruida: "217.568,83 m²",
            metragemTipo: "128,28 m² (Tipo 3A) a 135,29 m² (Tipo 3B)",
            coberturas: "290,73 m² Duplex com terraço gourmet",
            descricao: "7 arranha-céus de 36 andares. Suíte master com closet e varanda gourmet com churrasqueira.",
            corDestaque: "#10b981",
            statusObra: { progressoGeral: 92, fase: "Blocos A-C Entregues / Bloco D Acabamento", status: "em_obras" },
            posicaoCentro: { x: -80, z: -30 }
        },
        14: {
            id: 14,
            nome: "Grupo 14",
            endereco: "Estrada São Judas, nº 190",
            tipologia: "2 Dormitórios",
            paridade: "par",
            glbSource: "Firenze_Pares.glb",
            torresQtd: 7,
            blocos: ["A", "B", "C", "D", "E", "F", "G"],
            andaresPorTorre: 28,
            aptosPorAndar: 8,
            aptosPorTorre: 224,
            totalApartamentos: 1568,
            subsolos: "2 a 4 pavimentos",
            areaTerreno: "33.862,21 m²",
            areaConstruida: "176.380,25 m²",
            metragemTipo: "79,84 m² a 82,00 m²",
            coberturas: "184,24 m² a 203,79 m²",
            descricao: "7 torres de 28 andares ao longo do eixo norte da alameda.",
            corDestaque: "#6366f1",
            statusObra: { progressoGeral: 85, fase: "Estrutura Concluída / Alvenaria Avançada", status: "em_obras" },
            posicaoCentro: { x: 0, z: -110 }
        },
        15: {
            id: 15,
            nome: "Grupo 15",
            endereco: "Av. João Paulo I, nº 1973",
            tipologia: "3 Dormitórios",
            paridade: "impar",
            glbSource: "Firenze_Impares.glb",
            torresQtd: 7,
            blocos: ["A", "B", "C", "D", "E", "F", "G"],
            andaresPorTorre: 36,
            aptosPorAndar: 4,
            aptosPorTorre: 144,
            totalApartamentos: 1008,
            subsolos: "3 pavimentos",
            areaTerreno: "32.456,10 m²",
            areaConstruida: "217.568,83 m²",
            metragemTipo: "125,00 m² a 135,29 m²",
            coberturas: "290,73 m² Duplex",
            descricao: "7 torres de 36 andares com vista panorâmica da colina e área verde preservada.",
            corDestaque: "#f59e0b",
            statusObra: { progressoGeral: 78, fase: "Torres A e B Entregues / Torres C-E em Obras", status: "em_obras" },
            posicaoCentro: { x: 80, z: -30 }
        },
        16: {
            id: 16,
            nome: "Grupo 16",
            endereco: "Estrada São Judas, nº 190",
            tipologia: "2 Dormitórios",
            paridade: "par",
            glbSource: "Firenze_Pares.glb",
            torresQtd: 7,
            blocos: ["A", "B", "C", "D", "E", "F", "G"],
            andaresPorTorre: 28,
            aptosPorAndar: 8,
            aptosPorTorre: 224,
            totalApartamentos: 1568,
            subsolos: "2 a 4 pavimentos",
            areaTerreno: "28.082,86 m²",
            areaConstruida: "175.087,81 m²",
            metragemTipo: "79,84 m² a 82,00 m²",
            coberturas: "184,24 m² a 203,79 m²",
            descricao: "7 torres de 28 andares com subsolos interligados e acesso rápido às portarias.",
            corDestaque: "#ec4899",
            statusObra: { progressoGeral: 65, fase: "Instalações e Fachada", status: "em_obras" },
            posicaoCentro: { x: 160, z: -100 }
        },
        17: {
            id: 17,
            nome: "Grupo 17",
            endereco: "Av. João Paulo I, nº 1973 (Próx. Essencis / Bacia)",
            tipologia: "3 Dormitórios",
            paridade: "impar",
            glbSource: "Firenze_Impares.glb",
            torresQtd: 7,
            blocos: ["A", "B", "C", "D", "E", "F", "G"],
            andaresPorTorre: 36,
            aptosPorAndar: 4,
            aptosPorTorre: 144,
            totalApartamentos: 1008,
            subsolos: "3 pavimentos",
            areaTerreno: "30.979,70 m²",
            areaConstruida: "217.120,66 m²",
            metragemTipo: "128,28 m² a 135,29 m²",
            coberturas: "290,73 m² Duplex",
            descricao: "7 torres de 36 andares com projeto paisagístico sofisticado ao sul do condomínio.",
            corDestaque: "#14b8a6",
            statusObra: { progressoGeral: 52, fase: "Estrutura Vertical em Andamento", status: "em_obras" },
            posicaoCentro: { x: 120, z: 80 }
        },
        18: {
            id: 18,
            nome: "Grupo 18",
            endereco: "Estrada São Judas, nº 190 (Margem da Represa)",
            tipologia: "2 Dormitórios",
            paridade: "par",
            glbSource: "Firenze_Pares.glb",
            torresQtd: 7,
            blocos: ["A", "B", "C", "D", "E", "F", "G"],
            andaresPorTorre: 28,
            aptosPorAndar: 8,
            aptosPorTorre: 224,
            totalApartamentos: 1568,
            subsolos: "2 a 4 pavimentos",
            areaTerreno: "30.294,66 m²",
            areaConstruida: "182.457,30 m²",
            metragemTipo: "79,84 m² a 82,00 m²",
            coberturas: "184,24 m² a 203,79 m²",
            descricao: "7 torres de 28 andares ao lado da preservação ambiental e da bacia da represa.",
            corDestaque: "#8b5cf6",
            statusObra: { progressoGeral: 40, fase: "Fundações e Primeiros Pavimentos", status: "em_obras" },
            posicaoCentro: { x: -100, z: 90 }
        }
    },
    plantas: {
        tipo3: {
            nome: "Apartamento Tipo 3 Dormitórios (Padrão 125m² - 135m²)",
            pavimento: "Pavimento tipo dos grupos ímpares (13, 15 e 17) • 4 apartamentos por andar",
            areaPrivativa: "128,28 m² - 135,29 m²",
            dormitorios: 3,
            suites: "1 suíte com closet privativo",
            banheiros: "2 banheiros sociais + 1 lavabo",
            ambientes: [
                "Living integrado para Sala de Estar e Jantar em 2 ambientes",
                "Varanda Gourmet ampla com churrasqueira a carvão e bancada em granito",
                "Suíte Master com espaço para closet planejado",
                "Dormitório 2 (Solteiro / Hóspedes)",
                "Dormitório 3 (Home Office / Solteiro)",
                "Cozinha ampla e ventilada",
                "Lavanderia / Área de Serviço independente",
                "Lavabo social",
                "Banheiro social completo"
            ],
            vagasGaragem: "1 a 2 vagas cobertas",
            peDireito: "2,70 m",
            destaque: "Varanda Gourmet de grandes dimensões integrada à sala, sensação de viver em uma casa suspensa."
        },
        tipo2: {
            nome: "Apartamento Tipo 2 Dormitórios (Padrão 80m² - 82m²)",
            pavimento: "Pavimento tipo dos grupos pares (12, 14, 16 e 18) • 8 apartamentos por andar",
            areaPrivativa: "79,84 m² - 82,00 m²",
            dormitorios: 2,
            suites: "Opção com 1 suíte",
            banheiros: "1 a 2 banheiros",
            ambientes: [
                "Sala de Estar e Jantar integrada",
                "Sacada Gourmet com ponto para churrasqueira",
                "Dormitório Casal",
                "Dormitório Solteiro",
                "Cozinha planejada integrada",
                "Área de Serviço ventilada",
                "Banheiro social"
            ],
            vagasGaragem: "1 vaga demarcada coberta",
            peDireito: "2,70 m",
            destaque: "Planta inteligente com excelente aproveitamento de cada metro quadrado e ótima ventilação."
        }
    },
    // FVS (Fichas de Verificação de Serviço / Qualidade de Obra)
    fvsList: [
        {
            id: "FVS-2026-089",
            torre: "Grupo 13 - Bloco B",
            pavimento: 15,
            unidade: "Apto 1502 (Tipo 3B)",
            servico: "Impermeabilização da Varanda Gourmet e Teste de Estanqueidade (72h)",
            inspetor: "Eng. Roberto Albuquerque (CREA 5061928)",
            data: "22/09/2026",
            resultado: "CONFORME",
            itensChecklist: [
                { item: "Regularização de caimento com argamassa 1%", status: "OK" },
                { item: "Aplicação de primer asfáltico em 2 demãos", status: "OK" },
                { item: "Manta asfáltica 4mm com reforço nos ralos", status: "OK" },
                { item: "Teste com lâmina de água de 10cm por 72 horas sem vazamento", status: "OK" },
                { item: "Proteção mecânica com tela estruturante", status: "OK" }
            ],
            fotos: ["foto_estanqueidade_1502.jpg", "foto_ralo_reforcado.jpg"]
        },
        {
            id: "FVS-2026-094",
            torre: "Grupo 15 - Bloco C",
            pavimento: 22,
            unidade: "Apto 2204 (Tipo 3A)",
            servico: "Assentamento de Caixilhos e Guarda-Corpo de Vidro da Sacada",
            inspetor: "Engª. Mariana Souza (CREA 5084912)",
            data: "24/09/2026",
            resultado: "CONFORME",
            itensChecklist: [
                { item: "Fixação mecânica com chumbadores de aço inox", status: "OK" },
                { item: "Prumo e nível das esquadrias dentro da tolerância NBR", status: "OK" },
                { item: "Vidro laminado 10mm com película de segurança", status: "OK" },
                { item: "Vedação perimetral com silicone estrutural neutro", status: "OK" }
            ],
            fotos: ["foto_guarda_corpo_2204.jpg"]
        },
        {
            id: "FVS-2026-101",
            torre: "Grupo 12 - Bloco D",
            pavimento: 8,
            unidade: "Apto 0806 (Tipo 2B)",
            servico: "Inspeção de Barramento Elétrico Blindado (Bus-Way) e Quadro de Disjuntores",
            inspetor: "Téc. Marcelo Ribeiro",
            data: "25/09/2026",
            resultado: "CONFORME_COM_RESTRICAO",
            itensChecklist: [
                { item: "Aperto de torque das conexões do barramento", status: "OK" },
                { item: "Identificação das fases e circuitos no QDF", status: "ATENCAO" },
                { item: "Teste de isolamento ôhmico com megômetro", status: "OK" },
                { item: "Disjuntores diferenciais residuais (DR) atuando", status: "OK" }
            ],
            fotos: ["foto_qdf_0806.jpg"]
        }
    ],
    // Ocorrências e Não Conformidades Georreferenciadas no Modelo 3D
    ocorrenciasList: [
        {
            id: "OCORR-401",
            torreKey: "G13_BLOCO_C",
            torreNome: "Grupo 13 - Bloco C",
            pavimento: 24,
            unidade: "Apto 2401",
            severidade: "ALTA",
            corPin: "#f97316",
            titulo: "Infiltração identificada na junta da fachada externa",
            descricao: "Verificado ponto de umidade na parede externa do dormitório 2 após teste hidrostático.",
            status: "EM_TRATAMENTO",
            posicao3D: { x: -50, y: 26, z: -52 },
            responsavel: "Equipe de Fachadas Vida Nova",
            prazo: "28/09/2026"
        },
        {
            id: "OCORR-402",
            torreKey: "G15_BLOCO_D",
            torreNome: "Grupo 15 - Bloco D",
            pavimento: 12,
            unidade: "Apto 1203",
            severidade: "MEDIA",
            corPin: "#eab308",
            titulo: "Ajuste fino no prumo da porta da varanda gourmet",
            descricao: "Folga de 3mm no fechamento da porta balcão de correr de alumínio.",
            status: "ABERTA",
            posicao3D: { x: 50, y: 16, z: -25 },
            responsavel: "Empreiteira de Esquadrias",
            prazo: "30/09/2026"
        },
        {
            id: "OCORR-403",
            torreKey: "G18_BLOCO_A",
            torreNome: "Grupo 18 - Bloco A",
            pavimento: 2,
            unidade: "Subsolo Garagem 1",
            severidade: "CRITICA",
            corPin: "#ef4444",
            titulo: "Revisão do sistema de drenagem da caixa pluvial",
            descricao: "Bomba submersível do poço de recalque requer substituição do relé de nível.",
            status: "ABERTA",
            posicao3D: { x: -125, y: 3, z: 65 },
            responsavel: "Equipe de Hidráulica e Recalque",
            prazo: "27/09/2026"
        }
    ]
};
